//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBill
    {
        public int b_id { get; set; }
        public string s_name { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual CusService CusService { get; set; }
    }
}
